// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSmOH-w5oiqIvn8PmWSBTk6S6sSTb31z8',
    appId: '1:405406153615:web:3e5d74ac0bfbdd488e29fa',
    messagingSenderId: '405406153615',
    projectId: 'rentease-fc575',
    authDomain: 'rentease-fc575.firebaseapp.com',
    storageBucket: 'rentease-fc575.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmdcuvDy9ElUm1gPANCkRc73pmJ8xcimo',
    appId: '1:405406153615:android:b72c404f254786a58e29fa',
    messagingSenderId: '405406153615',
    projectId: 'rentease-fc575',
    storageBucket: 'rentease-fc575.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQlPbNIS1IHEI67COaO6OH4RQuhSKKSi8',
    appId: '1:405406153615:ios:dc57027ff8f4c6f38e29fa',
    messagingSenderId: '405406153615',
    projectId: 'rentease-fc575',
    storageBucket: 'rentease-fc575.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQlPbNIS1IHEI67COaO6OH4RQuhSKKSi8',
    appId: '1:405406153615:ios:dc57027ff8f4c6f38e29fa',
    messagingSenderId: '405406153615',
    projectId: 'rentease-fc575',
    storageBucket: 'rentease-fc575.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSmOH-w5oiqIvn8PmWSBTk6S6sSTb31z8',
    appId: '1:405406153615:web:162eabf7be65ab8b8e29fa',
    messagingSenderId: '405406153615',
    projectId: 'rentease-fc575',
    authDomain: 'rentease-fc575.firebaseapp.com',
    storageBucket: 'rentease-fc575.firebasestorage.app',
  );
}
